---
jupyter:
  jupytext:
    formats: ipynb,Rmd,R
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.9.1
  kernelspec:
    display_name: R
    language: R
    name: ir
output: pdf_document
---

# KNN Regression


```{r}
library('caret')
```

# simulation

```{r}
?runif
```

```{r}
x = runif(100,-1,1)
x_ord = order(x)
hist(x)
```

```{r}
y = x^2 # f(x) = x^2
plot(x,y)
```

```{r}
e = rnorm(100,0,1/10)
hist(e)
```

```{r}
y = x^2 + e
plot(x,y)
```

# using linear regression

```{r}
mod = lm(y~x) # y = b0 + b1*x
summary(mod)
```

```{r}
plot(x,y)
abline(coef(mod),col='red')
lines(x[x_ord],x[x_ord]^2,col='blue')
dim(model.matrix(mod))
```

# KNN

```{r}
?knnreg
```

```{r}
df = data.frame(x=x,y=y)
knn_mod = knnreg(y~.,data=df,k=10)
```

```{r}
xe = data.frame(x=sort(runif(1000,-1.5,1.5)))
```

```{r}
head(sample(predict(knn_mod,xe)))
```

```{r}
plot(xe$x,predict(knn_mod,xe),col='red',lwd=2,type='l',ylim=c(0,1.5))
points(x,y)
lines(xe$x,xe$x^2,col='blue',lwd=2)
```

## k = 3

```{r}
knn_mod = knnreg(y~.,data=df,k=3)
plot(x,y)
lines(xe$x,predict(knn_mod,xe),col='red')
lines(xe$x,xe$x^2,col='blue')
```

# k = 1

```{r}
knn_mod = knnreg(y~.,data=df,k=1)
plot(x,y)
lines(xe$x,predict(knn_mod,xe),col='red')
lines(xe$x,xe$x^2,col='blue')
```

# k = 50

```{r}
knn_mod = knnreg(y~.,data=df,k=50)
plot(x,y)
lines(xe$x,predict(knn_mod,xe),col='red')
lines(xe$x,xe$x^2,col='blue')
```

# k = 100

```{r}
knn_mod = knnreg(y~.,data=df,k=100)
plot(x,y)
lines(xe$x,predict(knn_mod,xe),col='red')
lines(xe$x,xe$x^2,col='blue')
#abline(h=mean(y),lty=2,col='orange')
```

```{r}
mean(y)
```

```{r}
head(predict(knn_mod))
```

# Can we do this with a linear model?

```{r}
lin_mod = lm(y~I(x^2)) # y = b0+b1x^2
plot(x,y)
lines(x[x_ord],predict(lin_mod)[x_ord],col='red')
lines(x[x_ord],x[x_ord]^2,col='blue')
```

```{r}
lin_mod = lm(y~x+I(x^4)) # y = b0+b1x^2
plot(x,y)
lines(x[x_ord],predict(lin_mod)[x_ord],col='red')
lines(x[x_ord],x[x_ord]^2,col='blue')
dim(model.matrix(lin_mod))
```

